languages:
 - c++
 - scala

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - python3

cache:
  directories:
    - obj/cache

matrix:
  include:
    - env:
      - CORE_GENERATOR=counter
      - SOC_GENERATOR=nop

before_install:
  - export MAKEFLAGS=-j3
  - export SCHEDULER=travis_wait
  - export SIMULATOR=icarus

script:
  - make makefrags
  - make
