languages:
 - c++
 - scala

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - python3

cache:
  directories:
    - obj/cache

matrix:
  include:
    - env:
      - CORE_GENERATOR=rocket-chip
      - SOC_GENERATOR=nop
    - env:
      - CORE_GENERATOR=rocket-chip
      - SOC_GENERATOR=bar-testchip
#    - env:
#      - CORE_GENERATOR=crossbar
#      - CORE_CONFIG=XBar2x2Config
#      - SOC_GENERATOR=nop

# blacklist private branches
branches:
  except:
    - hwacha

before_install:
  - export MAKEFLAGS=-j3
  - export SCHEDULER=travis_wait
  - export CORE_SIM_CONFIG=smoke

script:
  - make makefrags
  - make core-verilog
  - make core-simulator
  - make soc-verilog
  - make soc-simulator
  - make syn-verilog
  - make
