languages:
 - c++
 - scala

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo

matrix:
  include:
    - env:
      - CORE_GENERATOR=rocket-chip
      - SOC_GENERATOR=nop
    - env:
      - CORE_GENERATOR=rocket-chip
      - SOC_GENERATOR=bar-testchip
#    - env:
#      - CORE_GENERATOR=crossbar
#      - CORE_CONFIG=XBar2x2Config
#      - SOC_GENERATOR=nop

before_install:
  - export CXX=g++-4.8
  - export CC=gcc-4.8
  - export MAKEFLAGS=-j3
  - export SCHEDULER=travis_wait

script:
  - make makefrags
  - make core-verilog core-simulator
  - make soc-verilog soc-simulator
